# Version
version: '3.8'

services:
  # web:
  #   container_name: web_sparda_development
  #   build:
  #     context: ./
  #     dockerfile: docker/web.dockerfile
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - fpm
  #   networks:
  #     - sparda_development_network
  #   volumes:
  #     - ./:/var/www/html

  app:
    container_name: app_sparda_development
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    restart: unless-stopped
    ports:
        - "127.0.0.2:8080:80"
    depends_on:
      - fpm
    networks:
      - sparda_development_network
    volumes:
      - ./:/var/www/html

  fpm:
    container_name: fpm_sparda_development
    build:
      context: ./
      dockerfile: docker/fpm.dockerfile
    restart: unless-stopped
    networks:
      - sparda_development_network
    volumes:
      - ./:/var/www/html
      - ./docker/auth.json:/root/.config/composer/auth.json

  db:
    image: mysql:8.0
    container_name: database_sparda_development
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - .env.database
    ports:
      - "127.0.0.2:6033:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - sparda_development_network

  selenium:
    container_name: selenium_sparda_development
    build:
      context: ./
      dockerfile: docker/selenium.dockerfile
    restart: unless-stopped
    depends_on:
      - app
    links:
      - app:sdnet.test
    networks:
      - sparda_development_network
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
    - DISPLAY=${DISPLAY}
  
networks:
  sparda_development_network:
    name: sparda_development_network