# Version
version: '3.8'

services:
  web:
    container_name: web_sparda_development
    build:
      context: ./
      dockerfile: docker/config/web.dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.2:8080:80"
    depends_on:
      - fpm
    networks:
      - sparda_cms_network
    volumes:
      - ./:/var/www/html

  # app:
  #   container_name: app_sparda_development
  #   build:
  #     context: ./
  #     dockerfile: docker/config/app.dockerfile
  #   restart: unless-stopped
  #   ports:
  #       - "127.0.0.2:8080:80"
  #   depends_on:
  #     - fpm
  #   networks:
  #     - sparda_cms_network
  #   volumes:
  #     - ./:/var/www/html

  fpm:
    container_name: fpm_sparda_development
    build:
      context: ./
      dockerfile: docker/config/fpm.dockerfile
    restart: unless-stopped
    networks:
      - sparda_cms_network
    volumes:
      - ./:/var/www/html
      - ./docker/config/auth.json:/root/.config/composer/auth.json

  db:
    image: mysql:8.0
    container_name: database_sparda_development
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - .env.database
    ports:
      - "127.0.0.2:6033:3306"
    volumes:
      - ./docker/data/db:/var/lib/mysql
    networks:
      - sparda_cms_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_sparda_development
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - "127.0.0.2:8081:80"
    networks:
      - sparda_cms_network

  node:
    container_name: node_sparda_development
    build:
      context: ./
      dockerfile: docker/config/node.dockerfile
    command: >
      bash -c "rm -fv node_modules
      && ln -s /home/node_modules /var/www/html/node_modules
      && sleep infinity"
    tty: true
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - sparda_cms_network

  selenium:
    container_name: selenium_sparda_development
    build:
      context: ./
      dockerfile: docker/config/selenium.dockerfile
    depends_on:
      - web
    links:
      - web:sdnet.test
    networks:
      - sparda_cms_network
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
    - DISPLAY=${DISPLAY}
  
networks:
  sparda_cms_network:
    name: sparda_cms_network